################################
        # Build Stage
################################

FROM node:25.9-alpine3.22 AS builder

WORKDIR /app

COPY package*.json/  ..

RUN npm ci 

COPY . . 
RUN npm run build 

################################
        # Runtime Stage
################################


FROM nginx:1.29.8-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=builder /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

