###############################
# Build Stage
###############################

FROM python:3.14-slim AS builder

WORKDIR /app

RUN pip install  --no-cache-dir  uv

COPY pyproject.toml .

COPY . .

RUN uv sync --no-dev


###############################
# Runtime Stage
###############################

###############################
# Runtime Stage
###############################

FROM python:3.14-slim

WORKDIR /app

# Install curl (needed for healthcheck)
RUN apt-get update && apt-get install -y curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m appuser

# Copy app
COPY --from=builder /app /app

RUN chown -R appuser:appuser /app

USER appuser

CMD ["/app/.venv/bin/python", "-m", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]