###############################
# Build Stage
###############################

FROM python:3.14-slim AS builder

WORKDIR /app

RUN pip install uv

COPY pyproject.toml .

COPY . .

RUN uv pip install --system .



###############################
# Runtime Stage
###############################

FROM python:3.14-slim

WORKDIR /app

# Create non-root user
RUN useradd -m appuser

# Copy dependencies
COPY --from=builder /usr/local /usr/local

# Copy app
COPY --from=builder /app /app

RUN chown -R appuser:appuser /app

USER appuser

CMD ["python", "-m", "uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8080"]