name: CI/CD Pipeline for 3 tier app (Fastapi, React and Postgres-Sql )

on:
  push:
    branches: [main]
  
jobs:

  compile:

    name: Compile and Build Validation
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout the code in the runner.
        uses: actions/checkout@v4
      
      - name: Verify docker's status
        run: |
          docker --version 
          docker info > /dev/null

      - name: Backend Code Compilation
        run: |
          cd backend
          docker build --target builder -t be-compile . 

      - name: Frontend Code compilation 
        run: |
          cd frontend
          docker build --target builder -t fe-compile .


  gitleaks:

    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Checkout the code in the runner.
        uses: actions/checkout@v4
        
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9 
        with: 
          args: detect --source . --exit-code 1  


  tests:

    name: Unit Test Backend and Frontend
    runs-on: ubuntu-latest
    needs: gitleaks

    steps:
      
      - name: Checkout the code in the runner.
        uses: actions/checkout@v4
      
      # Backend Test
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install uv 
        run: |
          pip install --upgrade uv 

      - name: Install Backend Dependencies
        run: | 
          cd backend
          uv sync 
      
      - name: Run Backend Unit test
        run: | 
          cd backend
          uv run pytest

      # Frontend Tests
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install Frontend Dependencies
        run: | 
          cd frontend
          npm ci 
      
      - name: Run Frontend tests
        run: |
          cd frontend 
          npm test -- --watch=false
  

  build:

    name: Build the docker image
    runs-on: ubuntu-latest
    needs: tests

    steps:  

      - name: Checkout the code in the runner.
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker hub 
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
    
      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: shalintim/fast-backend:latest
    
      
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: shalintim/fast-frontend:latest

  # push:


  # deploy:

